import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Paul',
      email: 'admin@dummy.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Steve',
      email: 'user@dummy.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Polo Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 19,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 68,
      description: 'Good slim shirt',
    },
    {
      name: 'Lacoste Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 22,
      brand: 'Lacoste',
      rating: 4.0,
      numReviews: 44,
      description: 'Expose with fit shirt',
    },
    {
      name: 'Tarocash Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 115,
      countInStock: 0,
      brand: 'Tarocash',
      rating: 4.7,
      numReviews: 37,
      description: 'Casual shirt for everyday use',
    },
    {
      name: 'Polo Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 140,
      countInStock: 25,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 59,
      description: 'Good quality slim fit pant',
    },
    {
      name: 'Lacoste Fit Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 180,
      countInStock: 15,
      brand: 'Lacoste',
      rating: 4.9,
      numReviews: 38,
      description: 'Nice fitting pant to show off!',
    },
    {
      name: 'Tarocash Slim Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 110,
      countInStock: 17,
      brand: 'Tarocash',
      rating: 4.8,
      numReviews: 45,
      description: 'Slim fit pant for official use',
    },
  ],
};

export default data;
