const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 68,
      description: "Good slim shirt",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 150,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 44,
      description: "Expose with fit shirt",
    },
    {
      _id: "3",
      name: "Tarocash Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 210,
      brand: "Tarocash",
      rating: 4.7,
      numReviews: 37,
      description: "Casual shirt for everyday use",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 140,
      brand: "Nike",
      rating: 4.7,
      numReviews: 59,
      description: "Good quality slim fit pant",
    },
    {
      _id: "5",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 180,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 38,
      description: "Nice fitting pant to show off!",
    },
    {
      _id: "7",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 150,
      brand: "Puma",
      rating: 4.8,
      numReviews: 45,
      description: "Slim fit pant for official use",
    },
  ],
};

export default data;
